import { CldImage } from 'next-cloudinary';
import Image from 'next/image';
import Link from 'next/link';
import { getAllBlogPosts } from '../../database/posts';
import styles from '../posts/page.module.scss';

interface Post {
  id: string;
  title: string;
  // Add other properties as needed
}

interface PostsPageProps {
  posts: Post[];
}

export const metadata = {
  title: 'Community',
  description: 'Generated by create next app',
};

export default function PostsPage({ posts }: PostsPageProps) {
  console.log('posts', posts);

  return (
    <main>
      <div className={styles.info}>
        <div className={styles.titleWrapper}>
          <h2>Community</h2>
        </div>
        <div className={styles.imageWrapper}>
          {posts && posts.length > 0 ? (
            posts.map((post) => (
              <div className={styles.card} key={`post-div-${post.id}`}>
                <div>
                  <CldImage
                    width="960"
                    height="600"
                    src="sample"
                    sizes="100vw"
                    alt="Description of my image"
                  />
                </div>
                <Link href={`/posts/${post.id}`}>
                  <a className={styles.name}>{post.title}</a>
                </Link>
              </div>
            ))
          ) : (
            <p>No posts available.</p>
          )}
        </div>
      </div>
    </main>
  );
}
