import { CldImage } from 'next-cloudinary';
import Image from 'next/image';
import Link from 'next/link';
import { getAllBlogPosts } from '../../database/posts';
import styles from '../posts/page.module.scss';

export const metadata = {
  title: 'Community',
  description: 'Generated by create next app',
};

export default async function PostsPage() {
  const posts = await getAllBlogPosts();
  console.log('posts', posts);

  return (
    <div className={styles.info}>
      <div className={styles.titleWrapper}>
        <h2>Community</h2>
      </div>
      <div className={styles.imageWrapper}>
        {posts && posts.length > 0 ? (
          posts.map((post) => (
            <div className={styles.card} key={`post-div-${post.id}`}>
              <Link href={`/posts/${post.id}`}>{post.title}</Link>
              <Image src={post.imageUrl} alt="image" width={300} height={300} />
            </div>
          ))
        ) : (
          <p>No posts available.</p>
        )}
      </div>
    </div>
  );
}
