import { CldImage } from 'next-cloudinary';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../../app/posts/post.page.module.scss';
import { getAllBlogPosts } from '../../database/posts';

export const metadata = {
  title: 'Community',
  description: 'Generated by create next app',
};

export default async function PostsPage() {
  const posts = await getAllBlogPosts();
  console.log('posts', posts);

  return (
    <div className={styles.info}>
      <div className={styles.titleWrapper}>
        <h2>Travel blog</h2>
      </div>
      <div className={styles.imageWrapper}>
        {posts && posts.length > 0 ? (
          posts.map((post) => (
            <Link
              href={`/posts/${post.postId}`}
              className={styles.card}
              key={`post-div-${post.id}`}
            >
              <div className={styles.imageContainer}>
                <Image
                  src={post.imageUrl}
                  alt="image"
                  width={400}
                  height={300}
                  className={styles.image}
                />
              </div>
              <div className={styles.titleLink}>{post.title}</div>
              <p>Posted by: {post.username}</p>
            </Link>
          ))
        ) : (
          <p>No posts available.</p>
        )}
      </div>
    </div>
  );
}
