import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Image from 'next/image';
import Link from 'next/link';
import { getUserBySessionToken } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';
import styles from './globals.scss';
import { ProfileButton } from './profile/[username]/ProfileButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Home page | Travel journey',
    template: '%s | Travel journey',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user =
    sessionToken && (await getUserBySessionToken(sessionToken.value));
  return (
    <html lang="en">
      <body>
        <div className="navHeader">
          <header>
            <nav className="navContainer">
              <ul>
                <Link href="/">
                  <Image
                    src="/images/logo.png"
                    alt="Logo"
                    width={200}
                    height={200}
                  />{' '}
                </Link>

                <li>
                  {user ? (
                    <>
                      <Link href={`/profile/${user.username}`}>
                        Hey {user.username}!
                      </Link>
                      <Link href="/createPosts">Create post</Link>
                      <Link href="/posts">Travel blog</Link>

                      {ProfileButton}
                      <LogoutButton />
                    </>
                  ) : (
                    <>
                      <button className="registerButton">
                        <Link href="/register">Register</Link>
                      </button>
                      <button className="loginButton">
                        <Link href="/login">Login</Link>
                      </button>
                    </>
                  )}
                </li>
              </ul>
            </nav>
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
