import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Home page | LOGO ',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return <html lang="en"></html>;
}
