import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getUserBySessionToken } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';
import styles from './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Home page | Travel journey',
    template: '%s | Travel journey',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user =
    sessionToken && (await getUserBySessionToken(sessionToken.value));
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <nav className={styles.navbar}>
            <h1>World travelers</h1>
            <ul className={styles.links}>
              <li>
                <Link href="/">Home</Link>
              </li>

              <li>
                <Link href="/posts">Community</Link>
              </li>
              <li>
                <Link href="/createPost">Create Post</Link>
              </li>

              <li>
                {user ? (
                  <>
                    <div>{user.username}</div>
                    <LogoutButton />
                  </>
                ) : (
                  <>
                    <Link href="/register">Register</Link>
                    <Link href="/login">Login</Link>
                  </>
                )}
              </li>
            </ul>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
